chore: pin @types/node to fix CI check failures (#912)
This PR pins @types/node at 24.1.0 in order to fix CI check failures

24.3.0 is causing errors such as:
```
../../../node_modules/@types/node/child_process.d.ts(309,9): error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.
```